#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCV.Facade
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SaipherControleVoo")]
	internal partial class SCVControleVooDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTB_SCV_AERONAVE(SCV.Entity.TB_SCV_AERONAVE instance);
    partial void UpdateTB_SCV_AERONAVE(SCV.Entity.TB_SCV_AERONAVE instance);
    partial void DeleteTB_SCV_AERONAVE(SCV.Entity.TB_SCV_AERONAVE instance);
    partial void InsertTB_SCV_CENTRO_OPERACAO(SCV.Entity.TB_SCV_CENTRO_OPERACAO instance);
    partial void UpdateTB_SCV_CENTRO_OPERACAO(SCV.Entity.TB_SCV_CENTRO_OPERACAO instance);
    partial void DeleteTB_SCV_CENTRO_OPERACAO(SCV.Entity.TB_SCV_CENTRO_OPERACAO instance);
    partial void InsertTB_SCV_COMPANHIA(SCV.Entity.TB_SCV_COMPANHIA instance);
    partial void UpdateTB_SCV_COMPANHIA(SCV.Entity.TB_SCV_COMPANHIA instance);
    partial void DeleteTB_SCV_COMPANHIA(SCV.Entity.TB_SCV_COMPANHIA instance);
    partial void InsertTB_SCV_FABRICANTE(SCV.Entity.TB_SCV_FABRICANTE instance);
    partial void UpdateTB_SCV_FABRICANTE(SCV.Entity.TB_SCV_FABRICANTE instance);
    partial void DeleteTB_SCV_FABRICANTE(SCV.Entity.TB_SCV_FABRICANTE instance);
    partial void InsertTB_SCV_FROTA(SCV.Entity.TB_SCV_FROTA instance);
    partial void UpdateTB_SCV_FROTA(SCV.Entity.TB_SCV_FROTA instance);
    partial void DeleteTB_SCV_FROTA(SCV.Entity.TB_SCV_FROTA instance);
    partial void InsertTB_SCV_PLANO_VOO(SCV.Entity.TB_SCV_PLANO_VOO instance);
    partial void UpdateTB_SCV_PLANO_VOO(SCV.Entity.TB_SCV_PLANO_VOO instance);
    partial void DeleteTB_SCV_PLANO_VOO(SCV.Entity.TB_SCV_PLANO_VOO instance);
    #endregion
		
		public SCVControleVooDataContext() : 
				base(global::SCV.DataObjects.Properties.Settings.Default.SaipherControleVooConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SCVControleVooDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SCVControleVooDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SCVControleVooDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SCVControleVooDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<SCV.Entity.TB_SCV_AERONAVE> TB_SCV_AERONAVE
		{
			get
			{
				return this.GetTable<SCV.Entity.TB_SCV_AERONAVE>();
			}
		}
		
		public System.Data.Linq.Table<SCV.Entity.TB_SCV_CENTRO_OPERACAO> TB_SCV_CENTRO_OPERACAO
		{
			get
			{
				return this.GetTable<SCV.Entity.TB_SCV_CENTRO_OPERACAO>();
			}
		}
		
		public System.Data.Linq.Table<SCV.Entity.TB_SCV_COMPANHIA> TB_SCV_COMPANHIA
		{
			get
			{
				return this.GetTable<SCV.Entity.TB_SCV_COMPANHIA>();
			}
		}
		
		public System.Data.Linq.Table<SCV.Entity.TB_SCV_FABRICANTE> TB_SCV_FABRICANTE
		{
			get
			{
				return this.GetTable<SCV.Entity.TB_SCV_FABRICANTE>();
			}
		}
		
		public System.Data.Linq.Table<SCV.Entity.TB_SCV_FROTA> TB_SCV_FROTA
		{
			get
			{
				return this.GetTable<SCV.Entity.TB_SCV_FROTA>();
			}
		}
		
		public System.Data.Linq.Table<SCV.Entity.VW_SCV_FROTA_AERONAVE> VW_SCV_FROTA_AERONAVE
		{
			get
			{
				return this.GetTable<SCV.Entity.VW_SCV_FROTA_AERONAVE>();
			}
		}
		
		public System.Data.Linq.Table<SCV.Entity.TB_SCV_PLANO_VOO> TB_SCV_PLANO_VOO
		{
			get
			{
				return this.GetTable<SCV.Entity.TB_SCV_PLANO_VOO>();
			}
		}
		
		public System.Data.Linq.Table<SCV.Entity.VW_SCV_PLANO_VOO_INFORMACAO> VW_SCV_PLANO_VOO_INFORMACAO
		{
			get
			{
				return this.GetTable<SCV.Entity.VW_SCV_PLANO_VOO_INFORMACAO>();
			}
		}
	}
}
namespace SCV.Entity
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_SCV_AERONAVE")]
	public partial class TB_SCV_AERONAVE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_SCV_AERONAVE;
		
		private int _FK_SCV_FABRICANTE;
		
		private string _NM_NOME_AERONAVE;
		
		private string _NM_MODELO;
		
		private System.Nullable<int> _NR_PASSAGEIROS;
		
		private System.DateTime _DT_CADASTRO;
		
		private System.DateTime _DT_ATUALIZACAO;
		
		private EntitySet<TB_SCV_FROTA> _TB_SCV_FROTA;
		
		private EntityRef<TB_SCV_FABRICANTE> _TB_SCV_FABRICANTE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_SCV_AERONAVEChanging(int value);
    partial void OnID_SCV_AERONAVEChanged();
    partial void OnFK_SCV_FABRICANTEChanging(int value);
    partial void OnFK_SCV_FABRICANTEChanged();
    partial void OnNM_NOME_AERONAVEChanging(string value);
    partial void OnNM_NOME_AERONAVEChanged();
    partial void OnNM_MODELOChanging(string value);
    partial void OnNM_MODELOChanged();
    partial void OnNR_PASSAGEIROSChanging(System.Nullable<int> value);
    partial void OnNR_PASSAGEIROSChanged();
    partial void OnDT_CADASTROChanging(System.DateTime value);
    partial void OnDT_CADASTROChanged();
    partial void OnDT_ATUALIZACAOChanging(System.DateTime value);
    partial void OnDT_ATUALIZACAOChanged();
    #endregion
		
		public TB_SCV_AERONAVE()
		{
			this._TB_SCV_FROTA = new EntitySet<TB_SCV_FROTA>(new Action<TB_SCV_FROTA>(this.attach_TB_SCV_FROTA), new Action<TB_SCV_FROTA>(this.detach_TB_SCV_FROTA));
			this._TB_SCV_FABRICANTE = default(EntityRef<TB_SCV_FABRICANTE>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_SCV_AERONAVE", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_SCV_AERONAVE
		{
			get
			{
				return this._ID_SCV_AERONAVE;
			}
			set
			{
				if ((this._ID_SCV_AERONAVE != value))
				{
					this.OnID_SCV_AERONAVEChanging(value);
					this.SendPropertyChanging();
					this._ID_SCV_AERONAVE = value;
					this.SendPropertyChanged("ID_SCV_AERONAVE");
					this.OnID_SCV_AERONAVEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_SCV_FABRICANTE", DbType="Int NOT NULL")]
		public int FK_SCV_FABRICANTE
		{
			get
			{
				return this._FK_SCV_FABRICANTE;
			}
			set
			{
				if ((this._FK_SCV_FABRICANTE != value))
				{
					if (this._TB_SCV_FABRICANTE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFK_SCV_FABRICANTEChanging(value);
					this.SendPropertyChanging();
					this._FK_SCV_FABRICANTE = value;
					this.SendPropertyChanged("FK_SCV_FABRICANTE");
					this.OnFK_SCV_FABRICANTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NM_NOME_AERONAVE", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NM_NOME_AERONAVE
		{
			get
			{
				return this._NM_NOME_AERONAVE;
			}
			set
			{
				if ((this._NM_NOME_AERONAVE != value))
				{
					this.OnNM_NOME_AERONAVEChanging(value);
					this.SendPropertyChanging();
					this._NM_NOME_AERONAVE = value;
					this.SendPropertyChanged("NM_NOME_AERONAVE");
					this.OnNM_NOME_AERONAVEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NM_MODELO", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string NM_MODELO
		{
			get
			{
				return this._NM_MODELO;
			}
			set
			{
				if ((this._NM_MODELO != value))
				{
					this.OnNM_MODELOChanging(value);
					this.SendPropertyChanging();
					this._NM_MODELO = value;
					this.SendPropertyChanged("NM_MODELO");
					this.OnNM_MODELOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NR_PASSAGEIROS", DbType="Int")]
		public System.Nullable<int> NR_PASSAGEIROS
		{
			get
			{
				return this._NR_PASSAGEIROS;
			}
			set
			{
				if ((this._NR_PASSAGEIROS != value))
				{
					this.OnNR_PASSAGEIROSChanging(value);
					this.SendPropertyChanging();
					this._NR_PASSAGEIROS = value;
					this.SendPropertyChanged("NR_PASSAGEIROS");
					this.OnNR_PASSAGEIROSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DT_CADASTRO", DbType="DateTime NOT NULL")]
		public System.DateTime DT_CADASTRO
		{
			get
			{
				return this._DT_CADASTRO;
			}
			set
			{
				if ((this._DT_CADASTRO != value))
				{
					this.OnDT_CADASTROChanging(value);
					this.SendPropertyChanging();
					this._DT_CADASTRO = value;
					this.SendPropertyChanged("DT_CADASTRO");
					this.OnDT_CADASTROChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DT_ATUALIZACAO", DbType="DateTime NOT NULL")]
		public System.DateTime DT_ATUALIZACAO
		{
			get
			{
				return this._DT_ATUALIZACAO;
			}
			set
			{
				if ((this._DT_ATUALIZACAO != value))
				{
					this.OnDT_ATUALIZACAOChanging(value);
					this.SendPropertyChanging();
					this._DT_ATUALIZACAO = value;
					this.SendPropertyChanged("DT_ATUALIZACAO");
					this.OnDT_ATUALIZACAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_SCV_AERONAVE_TB_SCV_FROTA", Storage="_TB_SCV_FROTA", ThisKey="ID_SCV_AERONAVE", OtherKey="FK_SCV_AERONAVE")]
		public EntitySet<TB_SCV_FROTA> TB_SCV_FROTA
		{
			get
			{
				return this._TB_SCV_FROTA;
			}
			set
			{
				this._TB_SCV_FROTA.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_SCV_FABRICANTE_TB_SCV_AERONAVE", Storage="_TB_SCV_FABRICANTE", ThisKey="FK_SCV_FABRICANTE", OtherKey="ID_SCV_FABRICANTE", IsForeignKey=true)]
		public TB_SCV_FABRICANTE TB_SCV_FABRICANTE
		{
			get
			{
				return this._TB_SCV_FABRICANTE.Entity;
			}
			set
			{
				TB_SCV_FABRICANTE previousValue = this._TB_SCV_FABRICANTE.Entity;
				if (((previousValue != value) 
							|| (this._TB_SCV_FABRICANTE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TB_SCV_FABRICANTE.Entity = null;
						previousValue.TB_SCV_AERONAVE.Remove(this);
					}
					this._TB_SCV_FABRICANTE.Entity = value;
					if ((value != null))
					{
						value.TB_SCV_AERONAVE.Add(this);
						this._FK_SCV_FABRICANTE = value.ID_SCV_FABRICANTE;
					}
					else
					{
						this._FK_SCV_FABRICANTE = default(int);
					}
					this.SendPropertyChanged("TB_SCV_FABRICANTE");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TB_SCV_FROTA(TB_SCV_FROTA entity)
		{
			this.SendPropertyChanging();
			entity.TB_SCV_AERONAVE = this;
		}
		
		private void detach_TB_SCV_FROTA(TB_SCV_FROTA entity)
		{
			this.SendPropertyChanging();
			entity.TB_SCV_AERONAVE = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_SCV_CENTRO_OPERACAO")]
	public partial class TB_SCV_CENTRO_OPERACAO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_SCV_CENTRO_OPERACAO;
		
		private string _NM_CENTRO_OPERACAO;
		
		private string _NM_IATA;
		
		private string _NM_ICAO;
		
		private string _NM_LOCALIZACAO;
		
		private bool _BT_ATIVO;
		
		private System.DateTime _DT_CADASTRO;
		
		private System.DateTime _DT_ATUALIZACAO;
		
		private EntitySet<TB_SCV_PLANO_VOO> _TB_SCV_PLANO_VOO;
		
		private EntitySet<TB_SCV_PLANO_VOO> _TB_SCV_PLANO_VOO1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_SCV_CENTRO_OPERACAOChanging(int value);
    partial void OnID_SCV_CENTRO_OPERACAOChanged();
    partial void OnNM_CENTRO_OPERACAOChanging(string value);
    partial void OnNM_CENTRO_OPERACAOChanged();
    partial void OnNM_IATAChanging(string value);
    partial void OnNM_IATAChanged();
    partial void OnNM_ICAOChanging(string value);
    partial void OnNM_ICAOChanged();
    partial void OnNM_LOCALIZACAOChanging(string value);
    partial void OnNM_LOCALIZACAOChanged();
    partial void OnBT_ATIVOChanging(bool value);
    partial void OnBT_ATIVOChanged();
    partial void OnDT_CADASTROChanging(System.DateTime value);
    partial void OnDT_CADASTROChanged();
    partial void OnDT_ATUALIZACAOChanging(System.DateTime value);
    partial void OnDT_ATUALIZACAOChanged();
    #endregion
		
		public TB_SCV_CENTRO_OPERACAO()
		{
			this._TB_SCV_PLANO_VOO = new EntitySet<TB_SCV_PLANO_VOO>(new Action<TB_SCV_PLANO_VOO>(this.attach_TB_SCV_PLANO_VOO), new Action<TB_SCV_PLANO_VOO>(this.detach_TB_SCV_PLANO_VOO));
			this._TB_SCV_PLANO_VOO1 = new EntitySet<TB_SCV_PLANO_VOO>(new Action<TB_SCV_PLANO_VOO>(this.attach_TB_SCV_PLANO_VOO1), new Action<TB_SCV_PLANO_VOO>(this.detach_TB_SCV_PLANO_VOO1));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_SCV_CENTRO_OPERACAO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_SCV_CENTRO_OPERACAO
		{
			get
			{
				return this._ID_SCV_CENTRO_OPERACAO;
			}
			set
			{
				if ((this._ID_SCV_CENTRO_OPERACAO != value))
				{
					this.OnID_SCV_CENTRO_OPERACAOChanging(value);
					this.SendPropertyChanging();
					this._ID_SCV_CENTRO_OPERACAO = value;
					this.SendPropertyChanged("ID_SCV_CENTRO_OPERACAO");
					this.OnID_SCV_CENTRO_OPERACAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NM_CENTRO_OPERACAO", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string NM_CENTRO_OPERACAO
		{
			get
			{
				return this._NM_CENTRO_OPERACAO;
			}
			set
			{
				if ((this._NM_CENTRO_OPERACAO != value))
				{
					this.OnNM_CENTRO_OPERACAOChanging(value);
					this.SendPropertyChanging();
					this._NM_CENTRO_OPERACAO = value;
					this.SendPropertyChanged("NM_CENTRO_OPERACAO");
					this.OnNM_CENTRO_OPERACAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NM_IATA", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string NM_IATA
		{
			get
			{
				return this._NM_IATA;
			}
			set
			{
				if ((this._NM_IATA != value))
				{
					this.OnNM_IATAChanging(value);
					this.SendPropertyChanging();
					this._NM_IATA = value;
					this.SendPropertyChanged("NM_IATA");
					this.OnNM_IATAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NM_ICAO", DbType="VarChar(4) NOT NULL", CanBeNull=false)]
		public string NM_ICAO
		{
			get
			{
				return this._NM_ICAO;
			}
			set
			{
				if ((this._NM_ICAO != value))
				{
					this.OnNM_ICAOChanging(value);
					this.SendPropertyChanging();
					this._NM_ICAO = value;
					this.SendPropertyChanged("NM_ICAO");
					this.OnNM_ICAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NM_LOCALIZACAO", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string NM_LOCALIZACAO
		{
			get
			{
				return this._NM_LOCALIZACAO;
			}
			set
			{
				if ((this._NM_LOCALIZACAO != value))
				{
					this.OnNM_LOCALIZACAOChanging(value);
					this.SendPropertyChanging();
					this._NM_LOCALIZACAO = value;
					this.SendPropertyChanged("NM_LOCALIZACAO");
					this.OnNM_LOCALIZACAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BT_ATIVO", DbType="Bit NOT NULL")]
		public bool BT_ATIVO
		{
			get
			{
				return this._BT_ATIVO;
			}
			set
			{
				if ((this._BT_ATIVO != value))
				{
					this.OnBT_ATIVOChanging(value);
					this.SendPropertyChanging();
					this._BT_ATIVO = value;
					this.SendPropertyChanged("BT_ATIVO");
					this.OnBT_ATIVOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DT_CADASTRO", DbType="DateTime NOT NULL")]
		public System.DateTime DT_CADASTRO
		{
			get
			{
				return this._DT_CADASTRO;
			}
			set
			{
				if ((this._DT_CADASTRO != value))
				{
					this.OnDT_CADASTROChanging(value);
					this.SendPropertyChanging();
					this._DT_CADASTRO = value;
					this.SendPropertyChanged("DT_CADASTRO");
					this.OnDT_CADASTROChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DT_ATUALIZACAO", DbType="DateTime NOT NULL")]
		public System.DateTime DT_ATUALIZACAO
		{
			get
			{
				return this._DT_ATUALIZACAO;
			}
			set
			{
				if ((this._DT_ATUALIZACAO != value))
				{
					this.OnDT_ATUALIZACAOChanging(value);
					this.SendPropertyChanging();
					this._DT_ATUALIZACAO = value;
					this.SendPropertyChanged("DT_ATUALIZACAO");
					this.OnDT_ATUALIZACAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_SCV_CENTRO_OPERACAO_TB_SCV_PLANO_VOO", Storage="_TB_SCV_PLANO_VOO", ThisKey="ID_SCV_CENTRO_OPERACAO", OtherKey="FK_SCV_CENTRO_OPERACAO_ORIGEM")]
		public EntitySet<TB_SCV_PLANO_VOO> TB_SCV_PLANO_VOO
		{
			get
			{
				return this._TB_SCV_PLANO_VOO;
			}
			set
			{
				this._TB_SCV_PLANO_VOO.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_SCV_CENTRO_OPERACAO_TB_SCV_PLANO_VOO1", Storage="_TB_SCV_PLANO_VOO1", ThisKey="ID_SCV_CENTRO_OPERACAO", OtherKey="FK_SCV_CENTRO_OPERACAO_DESTINO")]
		public EntitySet<TB_SCV_PLANO_VOO> TB_SCV_PLANO_VOO1
		{
			get
			{
				return this._TB_SCV_PLANO_VOO1;
			}
			set
			{
				this._TB_SCV_PLANO_VOO1.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TB_SCV_PLANO_VOO(TB_SCV_PLANO_VOO entity)
		{
			this.SendPropertyChanging();
			entity.TB_SCV_CENTRO_OPERACAO = this;
		}
		
		private void detach_TB_SCV_PLANO_VOO(TB_SCV_PLANO_VOO entity)
		{
			this.SendPropertyChanging();
			entity.TB_SCV_CENTRO_OPERACAO = null;
		}
		
		private void attach_TB_SCV_PLANO_VOO1(TB_SCV_PLANO_VOO entity)
		{
			this.SendPropertyChanging();
			entity.TB_SCV_CENTRO_OPERACAO1 = this;
		}
		
		private void detach_TB_SCV_PLANO_VOO1(TB_SCV_PLANO_VOO entity)
		{
			this.SendPropertyChanging();
			entity.TB_SCV_CENTRO_OPERACAO1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_SCV_COMPANHIA")]
	public partial class TB_SCV_COMPANHIA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_SCV_COMPANHIA;
		
		private string _NM_COMPANHIA;
		
		private string _NM_IATA;
		
		private string _NM_ICAO;
		
		private string _NM_INDICATIVO_CHAMADA;
		
		private bool _BT_ATIVO;
		
		private System.DateTime _DT_CADASTRO;
		
		private System.DateTime _DT_ATUALIZACAO;
		
		private EntitySet<TB_SCV_FROTA> _TB_SCV_FROTA;
		
		private EntitySet<TB_SCV_PLANO_VOO> _TB_SCV_PLANO_VOO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_SCV_COMPANHIAChanging(int value);
    partial void OnID_SCV_COMPANHIAChanged();
    partial void OnNM_COMPANHIAChanging(string value);
    partial void OnNM_COMPANHIAChanged();
    partial void OnNM_IATAChanging(string value);
    partial void OnNM_IATAChanged();
    partial void OnNM_ICAOChanging(string value);
    partial void OnNM_ICAOChanged();
    partial void OnNM_INDICATIVO_CHAMADAChanging(string value);
    partial void OnNM_INDICATIVO_CHAMADAChanged();
    partial void OnBT_ATIVOChanging(bool value);
    partial void OnBT_ATIVOChanged();
    partial void OnDT_CADASTROChanging(System.DateTime value);
    partial void OnDT_CADASTROChanged();
    partial void OnDT_ATUALIZACAOChanging(System.DateTime value);
    partial void OnDT_ATUALIZACAOChanged();
    #endregion
		
		public TB_SCV_COMPANHIA()
		{
			this._TB_SCV_FROTA = new EntitySet<TB_SCV_FROTA>(new Action<TB_SCV_FROTA>(this.attach_TB_SCV_FROTA), new Action<TB_SCV_FROTA>(this.detach_TB_SCV_FROTA));
			this._TB_SCV_PLANO_VOO = new EntitySet<TB_SCV_PLANO_VOO>(new Action<TB_SCV_PLANO_VOO>(this.attach_TB_SCV_PLANO_VOO), new Action<TB_SCV_PLANO_VOO>(this.detach_TB_SCV_PLANO_VOO));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_SCV_COMPANHIA", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_SCV_COMPANHIA
		{
			get
			{
				return this._ID_SCV_COMPANHIA;
			}
			set
			{
				if ((this._ID_SCV_COMPANHIA != value))
				{
					this.OnID_SCV_COMPANHIAChanging(value);
					this.SendPropertyChanging();
					this._ID_SCV_COMPANHIA = value;
					this.SendPropertyChanged("ID_SCV_COMPANHIA");
					this.OnID_SCV_COMPANHIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NM_COMPANHIA", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string NM_COMPANHIA
		{
			get
			{
				return this._NM_COMPANHIA;
			}
			set
			{
				if ((this._NM_COMPANHIA != value))
				{
					this.OnNM_COMPANHIAChanging(value);
					this.SendPropertyChanging();
					this._NM_COMPANHIA = value;
					this.SendPropertyChanged("NM_COMPANHIA");
					this.OnNM_COMPANHIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NM_IATA", DbType="VarChar(2) NOT NULL", CanBeNull=false)]
		public string NM_IATA
		{
			get
			{
				return this._NM_IATA;
			}
			set
			{
				if ((this._NM_IATA != value))
				{
					this.OnNM_IATAChanging(value);
					this.SendPropertyChanging();
					this._NM_IATA = value;
					this.SendPropertyChanged("NM_IATA");
					this.OnNM_IATAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NM_ICAO", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string NM_ICAO
		{
			get
			{
				return this._NM_ICAO;
			}
			set
			{
				if ((this._NM_ICAO != value))
				{
					this.OnNM_ICAOChanging(value);
					this.SendPropertyChanging();
					this._NM_ICAO = value;
					this.SendPropertyChanged("NM_ICAO");
					this.OnNM_ICAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NM_INDICATIVO_CHAMADA", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string NM_INDICATIVO_CHAMADA
		{
			get
			{
				return this._NM_INDICATIVO_CHAMADA;
			}
			set
			{
				if ((this._NM_INDICATIVO_CHAMADA != value))
				{
					this.OnNM_INDICATIVO_CHAMADAChanging(value);
					this.SendPropertyChanging();
					this._NM_INDICATIVO_CHAMADA = value;
					this.SendPropertyChanged("NM_INDICATIVO_CHAMADA");
					this.OnNM_INDICATIVO_CHAMADAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BT_ATIVO", DbType="Bit NOT NULL")]
		public bool BT_ATIVO
		{
			get
			{
				return this._BT_ATIVO;
			}
			set
			{
				if ((this._BT_ATIVO != value))
				{
					this.OnBT_ATIVOChanging(value);
					this.SendPropertyChanging();
					this._BT_ATIVO = value;
					this.SendPropertyChanged("BT_ATIVO");
					this.OnBT_ATIVOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DT_CADASTRO", DbType="DateTime NOT NULL")]
		public System.DateTime DT_CADASTRO
		{
			get
			{
				return this._DT_CADASTRO;
			}
			set
			{
				if ((this._DT_CADASTRO != value))
				{
					this.OnDT_CADASTROChanging(value);
					this.SendPropertyChanging();
					this._DT_CADASTRO = value;
					this.SendPropertyChanged("DT_CADASTRO");
					this.OnDT_CADASTROChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DT_ATUALIZACAO", DbType="DateTime NOT NULL")]
		public System.DateTime DT_ATUALIZACAO
		{
			get
			{
				return this._DT_ATUALIZACAO;
			}
			set
			{
				if ((this._DT_ATUALIZACAO != value))
				{
					this.OnDT_ATUALIZACAOChanging(value);
					this.SendPropertyChanging();
					this._DT_ATUALIZACAO = value;
					this.SendPropertyChanged("DT_ATUALIZACAO");
					this.OnDT_ATUALIZACAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_SCV_COMPANHIA_TB_SCV_FROTA", Storage="_TB_SCV_FROTA", ThisKey="ID_SCV_COMPANHIA", OtherKey="FK_SCV_COMPANHIA")]
		public EntitySet<TB_SCV_FROTA> TB_SCV_FROTA
		{
			get
			{
				return this._TB_SCV_FROTA;
			}
			set
			{
				this._TB_SCV_FROTA.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_SCV_COMPANHIA_TB_SCV_PLANO_VOO", Storage="_TB_SCV_PLANO_VOO", ThisKey="ID_SCV_COMPANHIA", OtherKey="FK_SCV_COMPANHIA")]
		public EntitySet<TB_SCV_PLANO_VOO> TB_SCV_PLANO_VOO
		{
			get
			{
				return this._TB_SCV_PLANO_VOO;
			}
			set
			{
				this._TB_SCV_PLANO_VOO.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TB_SCV_FROTA(TB_SCV_FROTA entity)
		{
			this.SendPropertyChanging();
			entity.TB_SCV_COMPANHIA = this;
		}
		
		private void detach_TB_SCV_FROTA(TB_SCV_FROTA entity)
		{
			this.SendPropertyChanging();
			entity.TB_SCV_COMPANHIA = null;
		}
		
		private void attach_TB_SCV_PLANO_VOO(TB_SCV_PLANO_VOO entity)
		{
			this.SendPropertyChanging();
			entity.TB_SCV_COMPANHIA = this;
		}
		
		private void detach_TB_SCV_PLANO_VOO(TB_SCV_PLANO_VOO entity)
		{
			this.SendPropertyChanging();
			entity.TB_SCV_COMPANHIA = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_SCV_FABRICANTE")]
	public partial class TB_SCV_FABRICANTE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_SCV_FABRICANTE;
		
		private string _NM_RAZAO_SOCIAL;
		
		private string _NM_FABRICANTE;
		
		private string _NM_PAIS;
		
		private System.DateTime _DT_CADASTRO;
		
		private System.DateTime _DT_ALTERACAO;
		
		private EntitySet<TB_SCV_AERONAVE> _TB_SCV_AERONAVE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_SCV_FABRICANTEChanging(int value);
    partial void OnID_SCV_FABRICANTEChanged();
    partial void OnNM_RAZAO_SOCIALChanging(string value);
    partial void OnNM_RAZAO_SOCIALChanged();
    partial void OnNM_FABRICANTEChanging(string value);
    partial void OnNM_FABRICANTEChanged();
    partial void OnNM_PAISChanging(string value);
    partial void OnNM_PAISChanged();
    partial void OnDT_CADASTROChanging(System.DateTime value);
    partial void OnDT_CADASTROChanged();
    partial void OnDT_ALTERACAOChanging(System.DateTime value);
    partial void OnDT_ALTERACAOChanged();
    #endregion
		
		public TB_SCV_FABRICANTE()
		{
			this._TB_SCV_AERONAVE = new EntitySet<TB_SCV_AERONAVE>(new Action<TB_SCV_AERONAVE>(this.attach_TB_SCV_AERONAVE), new Action<TB_SCV_AERONAVE>(this.detach_TB_SCV_AERONAVE));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_SCV_FABRICANTE", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_SCV_FABRICANTE
		{
			get
			{
				return this._ID_SCV_FABRICANTE;
			}
			set
			{
				if ((this._ID_SCV_FABRICANTE != value))
				{
					this.OnID_SCV_FABRICANTEChanging(value);
					this.SendPropertyChanging();
					this._ID_SCV_FABRICANTE = value;
					this.SendPropertyChanged("ID_SCV_FABRICANTE");
					this.OnID_SCV_FABRICANTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NM_RAZAO_SOCIAL", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string NM_RAZAO_SOCIAL
		{
			get
			{
				return this._NM_RAZAO_SOCIAL;
			}
			set
			{
				if ((this._NM_RAZAO_SOCIAL != value))
				{
					this.OnNM_RAZAO_SOCIALChanging(value);
					this.SendPropertyChanging();
					this._NM_RAZAO_SOCIAL = value;
					this.SendPropertyChanged("NM_RAZAO_SOCIAL");
					this.OnNM_RAZAO_SOCIALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NM_FABRICANTE", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string NM_FABRICANTE
		{
			get
			{
				return this._NM_FABRICANTE;
			}
			set
			{
				if ((this._NM_FABRICANTE != value))
				{
					this.OnNM_FABRICANTEChanging(value);
					this.SendPropertyChanging();
					this._NM_FABRICANTE = value;
					this.SendPropertyChanged("NM_FABRICANTE");
					this.OnNM_FABRICANTEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NM_PAIS", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string NM_PAIS
		{
			get
			{
				return this._NM_PAIS;
			}
			set
			{
				if ((this._NM_PAIS != value))
				{
					this.OnNM_PAISChanging(value);
					this.SendPropertyChanging();
					this._NM_PAIS = value;
					this.SendPropertyChanged("NM_PAIS");
					this.OnNM_PAISChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DT_CADASTRO", DbType="DateTime NOT NULL")]
		public System.DateTime DT_CADASTRO
		{
			get
			{
				return this._DT_CADASTRO;
			}
			set
			{
				if ((this._DT_CADASTRO != value))
				{
					this.OnDT_CADASTROChanging(value);
					this.SendPropertyChanging();
					this._DT_CADASTRO = value;
					this.SendPropertyChanged("DT_CADASTRO");
					this.OnDT_CADASTROChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DT_ALTERACAO", DbType="DateTime NOT NULL")]
		public System.DateTime DT_ALTERACAO
		{
			get
			{
				return this._DT_ALTERACAO;
			}
			set
			{
				if ((this._DT_ALTERACAO != value))
				{
					this.OnDT_ALTERACAOChanging(value);
					this.SendPropertyChanging();
					this._DT_ALTERACAO = value;
					this.SendPropertyChanged("DT_ALTERACAO");
					this.OnDT_ALTERACAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_SCV_FABRICANTE_TB_SCV_AERONAVE", Storage="_TB_SCV_AERONAVE", ThisKey="ID_SCV_FABRICANTE", OtherKey="FK_SCV_FABRICANTE")]
		public EntitySet<TB_SCV_AERONAVE> TB_SCV_AERONAVE
		{
			get
			{
				return this._TB_SCV_AERONAVE;
			}
			set
			{
				this._TB_SCV_AERONAVE.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TB_SCV_AERONAVE(TB_SCV_AERONAVE entity)
		{
			this.SendPropertyChanging();
			entity.TB_SCV_FABRICANTE = this;
		}
		
		private void detach_TB_SCV_AERONAVE(TB_SCV_AERONAVE entity)
		{
			this.SendPropertyChanging();
			entity.TB_SCV_FABRICANTE = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_SCV_FROTA")]
	public partial class TB_SCV_FROTA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_SCV_FROTA;
		
		private int _FK_SCV_COMPANHIA;
		
		private int _FK_SCV_AERONAVE;
		
		private string _NM_MATRICULA;
		
		private long _NR_SERIE;
		
		private System.DateTime _DT_FABRICACAO;
		
		private System.DateTime _DT_COMPRA_TRANSFERENCIA;
		
		private bool _BT_ATIVO;
		
		private System.DateTime _DT_CADASTRO;
		
		private System.DateTime _DT_ATUALIZACAO;
		
		private EntitySet<TB_SCV_PLANO_VOO> _TB_SCV_PLANO_VOO;
		
		private EntityRef<TB_SCV_AERONAVE> _TB_SCV_AERONAVE;
		
		private EntityRef<TB_SCV_COMPANHIA> _TB_SCV_COMPANHIA;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_SCV_FROTAChanging(int value);
    partial void OnID_SCV_FROTAChanged();
    partial void OnFK_SCV_COMPANHIAChanging(int value);
    partial void OnFK_SCV_COMPANHIAChanged();
    partial void OnFK_SCV_AERONAVEChanging(int value);
    partial void OnFK_SCV_AERONAVEChanged();
    partial void OnNM_MATRICULAChanging(string value);
    partial void OnNM_MATRICULAChanged();
    partial void OnNR_SERIEChanging(long value);
    partial void OnNR_SERIEChanged();
    partial void OnDT_FABRICACAOChanging(System.DateTime value);
    partial void OnDT_FABRICACAOChanged();
    partial void OnDT_COMPRA_TRANSFERENCIAChanging(System.DateTime value);
    partial void OnDT_COMPRA_TRANSFERENCIAChanged();
    partial void OnBT_ATIVOChanging(bool value);
    partial void OnBT_ATIVOChanged();
    partial void OnDT_CADASTROChanging(System.DateTime value);
    partial void OnDT_CADASTROChanged();
    partial void OnDT_ATUALIZACAOChanging(System.DateTime value);
    partial void OnDT_ATUALIZACAOChanged();
    #endregion
		
		public TB_SCV_FROTA()
		{
			this._TB_SCV_PLANO_VOO = new EntitySet<TB_SCV_PLANO_VOO>(new Action<TB_SCV_PLANO_VOO>(this.attach_TB_SCV_PLANO_VOO), new Action<TB_SCV_PLANO_VOO>(this.detach_TB_SCV_PLANO_VOO));
			this._TB_SCV_AERONAVE = default(EntityRef<TB_SCV_AERONAVE>);
			this._TB_SCV_COMPANHIA = default(EntityRef<TB_SCV_COMPANHIA>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_SCV_FROTA", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_SCV_FROTA
		{
			get
			{
				return this._ID_SCV_FROTA;
			}
			set
			{
				if ((this._ID_SCV_FROTA != value))
				{
					this.OnID_SCV_FROTAChanging(value);
					this.SendPropertyChanging();
					this._ID_SCV_FROTA = value;
					this.SendPropertyChanged("ID_SCV_FROTA");
					this.OnID_SCV_FROTAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_SCV_COMPANHIA", DbType="Int NOT NULL")]
		public int FK_SCV_COMPANHIA
		{
			get
			{
				return this._FK_SCV_COMPANHIA;
			}
			set
			{
				if ((this._FK_SCV_COMPANHIA != value))
				{
					if (this._TB_SCV_COMPANHIA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFK_SCV_COMPANHIAChanging(value);
					this.SendPropertyChanging();
					this._FK_SCV_COMPANHIA = value;
					this.SendPropertyChanged("FK_SCV_COMPANHIA");
					this.OnFK_SCV_COMPANHIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_SCV_AERONAVE", DbType="Int NOT NULL")]
		public int FK_SCV_AERONAVE
		{
			get
			{
				return this._FK_SCV_AERONAVE;
			}
			set
			{
				if ((this._FK_SCV_AERONAVE != value))
				{
					if (this._TB_SCV_AERONAVE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFK_SCV_AERONAVEChanging(value);
					this.SendPropertyChanging();
					this._FK_SCV_AERONAVE = value;
					this.SendPropertyChanged("FK_SCV_AERONAVE");
					this.OnFK_SCV_AERONAVEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NM_MATRICULA", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string NM_MATRICULA
		{
			get
			{
				return this._NM_MATRICULA;
			}
			set
			{
				if ((this._NM_MATRICULA != value))
				{
					this.OnNM_MATRICULAChanging(value);
					this.SendPropertyChanging();
					this._NM_MATRICULA = value;
					this.SendPropertyChanged("NM_MATRICULA");
					this.OnNM_MATRICULAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NR_SERIE", DbType="BigInt NOT NULL")]
		public long NR_SERIE
		{
			get
			{
				return this._NR_SERIE;
			}
			set
			{
				if ((this._NR_SERIE != value))
				{
					this.OnNR_SERIEChanging(value);
					this.SendPropertyChanging();
					this._NR_SERIE = value;
					this.SendPropertyChanged("NR_SERIE");
					this.OnNR_SERIEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DT_FABRICACAO", DbType="Date NOT NULL")]
		public System.DateTime DT_FABRICACAO
		{
			get
			{
				return this._DT_FABRICACAO;
			}
			set
			{
				if ((this._DT_FABRICACAO != value))
				{
					this.OnDT_FABRICACAOChanging(value);
					this.SendPropertyChanging();
					this._DT_FABRICACAO = value;
					this.SendPropertyChanged("DT_FABRICACAO");
					this.OnDT_FABRICACAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DT_COMPRA_TRANSFERENCIA", DbType="Date NOT NULL")]
		public System.DateTime DT_COMPRA_TRANSFERENCIA
		{
			get
			{
				return this._DT_COMPRA_TRANSFERENCIA;
			}
			set
			{
				if ((this._DT_COMPRA_TRANSFERENCIA != value))
				{
					this.OnDT_COMPRA_TRANSFERENCIAChanging(value);
					this.SendPropertyChanging();
					this._DT_COMPRA_TRANSFERENCIA = value;
					this.SendPropertyChanged("DT_COMPRA_TRANSFERENCIA");
					this.OnDT_COMPRA_TRANSFERENCIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BT_ATIVO", DbType="Bit NOT NULL")]
		public bool BT_ATIVO
		{
			get
			{
				return this._BT_ATIVO;
			}
			set
			{
				if ((this._BT_ATIVO != value))
				{
					this.OnBT_ATIVOChanging(value);
					this.SendPropertyChanging();
					this._BT_ATIVO = value;
					this.SendPropertyChanged("BT_ATIVO");
					this.OnBT_ATIVOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DT_CADASTRO", DbType="DateTime NOT NULL")]
		public System.DateTime DT_CADASTRO
		{
			get
			{
				return this._DT_CADASTRO;
			}
			set
			{
				if ((this._DT_CADASTRO != value))
				{
					this.OnDT_CADASTROChanging(value);
					this.SendPropertyChanging();
					this._DT_CADASTRO = value;
					this.SendPropertyChanged("DT_CADASTRO");
					this.OnDT_CADASTROChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DT_ATUALIZACAO", DbType="DateTime NOT NULL")]
		public System.DateTime DT_ATUALIZACAO
		{
			get
			{
				return this._DT_ATUALIZACAO;
			}
			set
			{
				if ((this._DT_ATUALIZACAO != value))
				{
					this.OnDT_ATUALIZACAOChanging(value);
					this.SendPropertyChanging();
					this._DT_ATUALIZACAO = value;
					this.SendPropertyChanged("DT_ATUALIZACAO");
					this.OnDT_ATUALIZACAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_SCV_FROTA_TB_SCV_PLANO_VOO", Storage="_TB_SCV_PLANO_VOO", ThisKey="ID_SCV_FROTA", OtherKey="FK_SCV_FROTA")]
		public EntitySet<TB_SCV_PLANO_VOO> TB_SCV_PLANO_VOO
		{
			get
			{
				return this._TB_SCV_PLANO_VOO;
			}
			set
			{
				this._TB_SCV_PLANO_VOO.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_SCV_AERONAVE_TB_SCV_FROTA", Storage="_TB_SCV_AERONAVE", ThisKey="FK_SCV_AERONAVE", OtherKey="ID_SCV_AERONAVE", IsForeignKey=true)]
		public TB_SCV_AERONAVE TB_SCV_AERONAVE
		{
			get
			{
				return this._TB_SCV_AERONAVE.Entity;
			}
			set
			{
				TB_SCV_AERONAVE previousValue = this._TB_SCV_AERONAVE.Entity;
				if (((previousValue != value) 
							|| (this._TB_SCV_AERONAVE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TB_SCV_AERONAVE.Entity = null;
						previousValue.TB_SCV_FROTA.Remove(this);
					}
					this._TB_SCV_AERONAVE.Entity = value;
					if ((value != null))
					{
						value.TB_SCV_FROTA.Add(this);
						this._FK_SCV_AERONAVE = value.ID_SCV_AERONAVE;
					}
					else
					{
						this._FK_SCV_AERONAVE = default(int);
					}
					this.SendPropertyChanged("TB_SCV_AERONAVE");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_SCV_COMPANHIA_TB_SCV_FROTA", Storage="_TB_SCV_COMPANHIA", ThisKey="FK_SCV_COMPANHIA", OtherKey="ID_SCV_COMPANHIA", IsForeignKey=true)]
		public TB_SCV_COMPANHIA TB_SCV_COMPANHIA
		{
			get
			{
				return this._TB_SCV_COMPANHIA.Entity;
			}
			set
			{
				TB_SCV_COMPANHIA previousValue = this._TB_SCV_COMPANHIA.Entity;
				if (((previousValue != value) 
							|| (this._TB_SCV_COMPANHIA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TB_SCV_COMPANHIA.Entity = null;
						previousValue.TB_SCV_FROTA.Remove(this);
					}
					this._TB_SCV_COMPANHIA.Entity = value;
					if ((value != null))
					{
						value.TB_SCV_FROTA.Add(this);
						this._FK_SCV_COMPANHIA = value.ID_SCV_COMPANHIA;
					}
					else
					{
						this._FK_SCV_COMPANHIA = default(int);
					}
					this.SendPropertyChanged("TB_SCV_COMPANHIA");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TB_SCV_PLANO_VOO(TB_SCV_PLANO_VOO entity)
		{
			this.SendPropertyChanging();
			entity.TB_SCV_FROTA = this;
		}
		
		private void detach_TB_SCV_PLANO_VOO(TB_SCV_PLANO_VOO entity)
		{
			this.SendPropertyChanging();
			entity.TB_SCV_FROTA = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_SCV_FROTA_AERONAVE")]
	public partial class VW_SCV_FROTA_AERONAVE
	{
		
		private int _ID_SCV_FROTA;
		
		private int _ID_SCV_AERONAVE;
		
		private int _FK_SCV_COMPANHIA;
		
		private string _NM_MATRICULA;
		
		private long _NR_SERIE;
		
		private System.DateTime _DT_FABRICACAO;
		
		private System.DateTime _DT_COMPRA_TRANSFERENCIA;
		
		private string _NM_NOME_AERONAVE;
		
		private string _NM_MODELO;
		
		public VW_SCV_FROTA_AERONAVE()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_SCV_FROTA", DbType="Int NOT NULL")]
		public int ID_SCV_FROTA
		{
			get
			{
				return this._ID_SCV_FROTA;
			}
			set
			{
				if ((this._ID_SCV_FROTA != value))
				{
					this._ID_SCV_FROTA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_SCV_AERONAVE", DbType="Int NOT NULL")]
		public int ID_SCV_AERONAVE
		{
			get
			{
				return this._ID_SCV_AERONAVE;
			}
			set
			{
				if ((this._ID_SCV_AERONAVE != value))
				{
					this._ID_SCV_AERONAVE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_SCV_COMPANHIA", DbType="Int NOT NULL")]
		public int FK_SCV_COMPANHIA
		{
			get
			{
				return this._FK_SCV_COMPANHIA;
			}
			set
			{
				if ((this._FK_SCV_COMPANHIA != value))
				{
					this._FK_SCV_COMPANHIA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NM_MATRICULA", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string NM_MATRICULA
		{
			get
			{
				return this._NM_MATRICULA;
			}
			set
			{
				if ((this._NM_MATRICULA != value))
				{
					this._NM_MATRICULA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NR_SERIE", DbType="BigInt NOT NULL")]
		public long NR_SERIE
		{
			get
			{
				return this._NR_SERIE;
			}
			set
			{
				if ((this._NR_SERIE != value))
				{
					this._NR_SERIE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DT_FABRICACAO", DbType="Date NOT NULL")]
		public System.DateTime DT_FABRICACAO
		{
			get
			{
				return this._DT_FABRICACAO;
			}
			set
			{
				if ((this._DT_FABRICACAO != value))
				{
					this._DT_FABRICACAO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DT_COMPRA_TRANSFERENCIA", DbType="Date NOT NULL")]
		public System.DateTime DT_COMPRA_TRANSFERENCIA
		{
			get
			{
				return this._DT_COMPRA_TRANSFERENCIA;
			}
			set
			{
				if ((this._DT_COMPRA_TRANSFERENCIA != value))
				{
					this._DT_COMPRA_TRANSFERENCIA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NM_NOME_AERONAVE", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NM_NOME_AERONAVE
		{
			get
			{
				return this._NM_NOME_AERONAVE;
			}
			set
			{
				if ((this._NM_NOME_AERONAVE != value))
				{
					this._NM_NOME_AERONAVE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NM_MODELO", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string NM_MODELO
		{
			get
			{
				return this._NM_MODELO;
			}
			set
			{
				if ((this._NM_MODELO != value))
				{
					this._NM_MODELO = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TB_SCV_PLANO_VOO")]
	public partial class TB_SCV_PLANO_VOO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_SCV_PLANO_VOO;
		
		private int _FK_SCV_COMPANHIA;
		
		private int _FK_SCV_FROTA;
		
		private System.DateTime _DT_VOO;
		
		private int _FK_SCV_CENTRO_OPERACAO_ORIGEM;
		
		private int _FK_SCV_CENTRO_OPERACAO_DESTINO;
		
		private bool _BT_ATIVO;
		
		private System.DateTime _DT_ATUALIZACAO;
		
		private System.DateTime _DT_CADASTRO;
		
		private EntityRef<TB_SCV_CENTRO_OPERACAO> _TB_SCV_CENTRO_OPERACAO;
		
		private EntityRef<TB_SCV_CENTRO_OPERACAO> _TB_SCV_CENTRO_OPERACAO1;
		
		private EntityRef<TB_SCV_COMPANHIA> _TB_SCV_COMPANHIA;
		
		private EntityRef<TB_SCV_FROTA> _TB_SCV_FROTA;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_SCV_PLANO_VOOChanging(int value);
    partial void OnID_SCV_PLANO_VOOChanged();
    partial void OnFK_SCV_COMPANHIAChanging(int value);
    partial void OnFK_SCV_COMPANHIAChanged();
    partial void OnFK_SCV_FROTAChanging(int value);
    partial void OnFK_SCV_FROTAChanged();
    partial void OnDT_VOOChanging(System.DateTime value);
    partial void OnDT_VOOChanged();
    partial void OnFK_SCV_CENTRO_OPERACAO_ORIGEMChanging(int value);
    partial void OnFK_SCV_CENTRO_OPERACAO_ORIGEMChanged();
    partial void OnFK_SCV_CENTRO_OPERACAO_DESTINOChanging(int value);
    partial void OnFK_SCV_CENTRO_OPERACAO_DESTINOChanged();
    partial void OnBT_ATIVOChanging(bool value);
    partial void OnBT_ATIVOChanged();
    partial void OnDT_ATUALIZACAOChanging(System.DateTime value);
    partial void OnDT_ATUALIZACAOChanged();
    partial void OnDT_CADASTROChanging(System.DateTime value);
    partial void OnDT_CADASTROChanged();
    #endregion
		
		public TB_SCV_PLANO_VOO()
		{
			this._TB_SCV_CENTRO_OPERACAO = default(EntityRef<TB_SCV_CENTRO_OPERACAO>);
			this._TB_SCV_CENTRO_OPERACAO1 = default(EntityRef<TB_SCV_CENTRO_OPERACAO>);
			this._TB_SCV_COMPANHIA = default(EntityRef<TB_SCV_COMPANHIA>);
			this._TB_SCV_FROTA = default(EntityRef<TB_SCV_FROTA>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_SCV_PLANO_VOO", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_SCV_PLANO_VOO
		{
			get
			{
				return this._ID_SCV_PLANO_VOO;
			}
			set
			{
				if ((this._ID_SCV_PLANO_VOO != value))
				{
					this.OnID_SCV_PLANO_VOOChanging(value);
					this.SendPropertyChanging();
					this._ID_SCV_PLANO_VOO = value;
					this.SendPropertyChanged("ID_SCV_PLANO_VOO");
					this.OnID_SCV_PLANO_VOOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_SCV_COMPANHIA", DbType="Int NOT NULL")]
		public int FK_SCV_COMPANHIA
		{
			get
			{
				return this._FK_SCV_COMPANHIA;
			}
			set
			{
				if ((this._FK_SCV_COMPANHIA != value))
				{
					if (this._TB_SCV_COMPANHIA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFK_SCV_COMPANHIAChanging(value);
					this.SendPropertyChanging();
					this._FK_SCV_COMPANHIA = value;
					this.SendPropertyChanged("FK_SCV_COMPANHIA");
					this.OnFK_SCV_COMPANHIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_SCV_FROTA", DbType="Int NOT NULL")]
		public int FK_SCV_FROTA
		{
			get
			{
				return this._FK_SCV_FROTA;
			}
			set
			{
				if ((this._FK_SCV_FROTA != value))
				{
					if (this._TB_SCV_FROTA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFK_SCV_FROTAChanging(value);
					this.SendPropertyChanging();
					this._FK_SCV_FROTA = value;
					this.SendPropertyChanged("FK_SCV_FROTA");
					this.OnFK_SCV_FROTAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DT_VOO", DbType="DateTime NOT NULL")]
		public System.DateTime DT_VOO
		{
			get
			{
				return this._DT_VOO;
			}
			set
			{
				if ((this._DT_VOO != value))
				{
					this.OnDT_VOOChanging(value);
					this.SendPropertyChanging();
					this._DT_VOO = value;
					this.SendPropertyChanged("DT_VOO");
					this.OnDT_VOOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_SCV_CENTRO_OPERACAO_ORIGEM", DbType="Int NOT NULL")]
		public int FK_SCV_CENTRO_OPERACAO_ORIGEM
		{
			get
			{
				return this._FK_SCV_CENTRO_OPERACAO_ORIGEM;
			}
			set
			{
				if ((this._FK_SCV_CENTRO_OPERACAO_ORIGEM != value))
				{
					if (this._TB_SCV_CENTRO_OPERACAO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFK_SCV_CENTRO_OPERACAO_ORIGEMChanging(value);
					this.SendPropertyChanging();
					this._FK_SCV_CENTRO_OPERACAO_ORIGEM = value;
					this.SendPropertyChanged("FK_SCV_CENTRO_OPERACAO_ORIGEM");
					this.OnFK_SCV_CENTRO_OPERACAO_ORIGEMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_SCV_CENTRO_OPERACAO_DESTINO", DbType="Int NOT NULL")]
		public int FK_SCV_CENTRO_OPERACAO_DESTINO
		{
			get
			{
				return this._FK_SCV_CENTRO_OPERACAO_DESTINO;
			}
			set
			{
				if ((this._FK_SCV_CENTRO_OPERACAO_DESTINO != value))
				{
					if (this._TB_SCV_CENTRO_OPERACAO1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFK_SCV_CENTRO_OPERACAO_DESTINOChanging(value);
					this.SendPropertyChanging();
					this._FK_SCV_CENTRO_OPERACAO_DESTINO = value;
					this.SendPropertyChanged("FK_SCV_CENTRO_OPERACAO_DESTINO");
					this.OnFK_SCV_CENTRO_OPERACAO_DESTINOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BT_ATIVO", DbType="Bit NOT NULL")]
		public bool BT_ATIVO
		{
			get
			{
				return this._BT_ATIVO;
			}
			set
			{
				if ((this._BT_ATIVO != value))
				{
					this.OnBT_ATIVOChanging(value);
					this.SendPropertyChanging();
					this._BT_ATIVO = value;
					this.SendPropertyChanged("BT_ATIVO");
					this.OnBT_ATIVOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DT_ATUALIZACAO", DbType="DateTime NOT NULL")]
		public System.DateTime DT_ATUALIZACAO
		{
			get
			{
				return this._DT_ATUALIZACAO;
			}
			set
			{
				if ((this._DT_ATUALIZACAO != value))
				{
					this.OnDT_ATUALIZACAOChanging(value);
					this.SendPropertyChanging();
					this._DT_ATUALIZACAO = value;
					this.SendPropertyChanged("DT_ATUALIZACAO");
					this.OnDT_ATUALIZACAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DT_CADASTRO", DbType="DateTime NOT NULL")]
		public System.DateTime DT_CADASTRO
		{
			get
			{
				return this._DT_CADASTRO;
			}
			set
			{
				if ((this._DT_CADASTRO != value))
				{
					this.OnDT_CADASTROChanging(value);
					this.SendPropertyChanging();
					this._DT_CADASTRO = value;
					this.SendPropertyChanged("DT_CADASTRO");
					this.OnDT_CADASTROChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_SCV_CENTRO_OPERACAO_TB_SCV_PLANO_VOO", Storage="_TB_SCV_CENTRO_OPERACAO", ThisKey="FK_SCV_CENTRO_OPERACAO_ORIGEM", OtherKey="ID_SCV_CENTRO_OPERACAO", IsForeignKey=true)]
		public TB_SCV_CENTRO_OPERACAO TB_SCV_CENTRO_OPERACAO
		{
			get
			{
				return this._TB_SCV_CENTRO_OPERACAO.Entity;
			}
			set
			{
				TB_SCV_CENTRO_OPERACAO previousValue = this._TB_SCV_CENTRO_OPERACAO.Entity;
				if (((previousValue != value) 
							|| (this._TB_SCV_CENTRO_OPERACAO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TB_SCV_CENTRO_OPERACAO.Entity = null;
						previousValue.TB_SCV_PLANO_VOO.Remove(this);
					}
					this._TB_SCV_CENTRO_OPERACAO.Entity = value;
					if ((value != null))
					{
						value.TB_SCV_PLANO_VOO.Add(this);
						this._FK_SCV_CENTRO_OPERACAO_ORIGEM = value.ID_SCV_CENTRO_OPERACAO;
					}
					else
					{
						this._FK_SCV_CENTRO_OPERACAO_ORIGEM = default(int);
					}
					this.SendPropertyChanged("TB_SCV_CENTRO_OPERACAO");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_SCV_CENTRO_OPERACAO_TB_SCV_PLANO_VOO1", Storage="_TB_SCV_CENTRO_OPERACAO1", ThisKey="FK_SCV_CENTRO_OPERACAO_DESTINO", OtherKey="ID_SCV_CENTRO_OPERACAO", IsForeignKey=true)]
		public TB_SCV_CENTRO_OPERACAO TB_SCV_CENTRO_OPERACAO1
		{
			get
			{
				return this._TB_SCV_CENTRO_OPERACAO1.Entity;
			}
			set
			{
				TB_SCV_CENTRO_OPERACAO previousValue = this._TB_SCV_CENTRO_OPERACAO1.Entity;
				if (((previousValue != value) 
							|| (this._TB_SCV_CENTRO_OPERACAO1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TB_SCV_CENTRO_OPERACAO1.Entity = null;
						previousValue.TB_SCV_PLANO_VOO1.Remove(this);
					}
					this._TB_SCV_CENTRO_OPERACAO1.Entity = value;
					if ((value != null))
					{
						value.TB_SCV_PLANO_VOO1.Add(this);
						this._FK_SCV_CENTRO_OPERACAO_DESTINO = value.ID_SCV_CENTRO_OPERACAO;
					}
					else
					{
						this._FK_SCV_CENTRO_OPERACAO_DESTINO = default(int);
					}
					this.SendPropertyChanged("TB_SCV_CENTRO_OPERACAO1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_SCV_COMPANHIA_TB_SCV_PLANO_VOO", Storage="_TB_SCV_COMPANHIA", ThisKey="FK_SCV_COMPANHIA", OtherKey="ID_SCV_COMPANHIA", IsForeignKey=true)]
		public TB_SCV_COMPANHIA TB_SCV_COMPANHIA
		{
			get
			{
				return this._TB_SCV_COMPANHIA.Entity;
			}
			set
			{
				TB_SCV_COMPANHIA previousValue = this._TB_SCV_COMPANHIA.Entity;
				if (((previousValue != value) 
							|| (this._TB_SCV_COMPANHIA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TB_SCV_COMPANHIA.Entity = null;
						previousValue.TB_SCV_PLANO_VOO.Remove(this);
					}
					this._TB_SCV_COMPANHIA.Entity = value;
					if ((value != null))
					{
						value.TB_SCV_PLANO_VOO.Add(this);
						this._FK_SCV_COMPANHIA = value.ID_SCV_COMPANHIA;
					}
					else
					{
						this._FK_SCV_COMPANHIA = default(int);
					}
					this.SendPropertyChanged("TB_SCV_COMPANHIA");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TB_SCV_FROTA_TB_SCV_PLANO_VOO", Storage="_TB_SCV_FROTA", ThisKey="FK_SCV_FROTA", OtherKey="ID_SCV_FROTA", IsForeignKey=true)]
		public TB_SCV_FROTA TB_SCV_FROTA
		{
			get
			{
				return this._TB_SCV_FROTA.Entity;
			}
			set
			{
				TB_SCV_FROTA previousValue = this._TB_SCV_FROTA.Entity;
				if (((previousValue != value) 
							|| (this._TB_SCV_FROTA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TB_SCV_FROTA.Entity = null;
						previousValue.TB_SCV_PLANO_VOO.Remove(this);
					}
					this._TB_SCV_FROTA.Entity = value;
					if ((value != null))
					{
						value.TB_SCV_PLANO_VOO.Add(this);
						this._FK_SCV_FROTA = value.ID_SCV_FROTA;
					}
					else
					{
						this._FK_SCV_FROTA = default(int);
					}
					this.SendPropertyChanged("TB_SCV_FROTA");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VW_SCV_PLANO_VOO_INFORMACAO")]
	public partial class VW_SCV_PLANO_VOO_INFORMACAO
	{
		
		private int _ID_SCV_PLANO_VOO;
		
		private int _ID_SCV_COMPANHIA;
		
		private int _ID_SCV_FROTA;
		
		private int _ID_SCV_CENTRO_OPERACAO_ORIGEM;
		
		private int _ID_SCV_CENTRO_OPERACAO_DESTINO;
		
		private string _NUMERO_VOO;
		
		private System.DateTime _DT_VOO;
		
		private System.DateTime _DT_CADASTRO;
		
		private System.DateTime _DT_ATUALIZACAO;
		
		private string _NM_COMPANHIA;
		
		private string _COMPANHIA_ICAO;
		
		private string _NM_NOME_AERONAVE;
		
		private string _NM_MATRICULA;
		
		private long _NR_SERIE;
		
		private string _CENTRO_OPERACAO_ORIGEM;
		
		private string _CENTRO_OPERACAO_DESTINO;
		
		public VW_SCV_PLANO_VOO_INFORMACAO()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_SCV_PLANO_VOO", DbType="Int NOT NULL")]
		public int ID_SCV_PLANO_VOO
		{
			get
			{
				return this._ID_SCV_PLANO_VOO;
			}
			set
			{
				if ((this._ID_SCV_PLANO_VOO != value))
				{
					this._ID_SCV_PLANO_VOO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_SCV_COMPANHIA", DbType="Int NOT NULL")]
		public int ID_SCV_COMPANHIA
		{
			get
			{
				return this._ID_SCV_COMPANHIA;
			}
			set
			{
				if ((this._ID_SCV_COMPANHIA != value))
				{
					this._ID_SCV_COMPANHIA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_SCV_FROTA", DbType="Int NOT NULL")]
		public int ID_SCV_FROTA
		{
			get
			{
				return this._ID_SCV_FROTA;
			}
			set
			{
				if ((this._ID_SCV_FROTA != value))
				{
					this._ID_SCV_FROTA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_SCV_CENTRO_OPERACAO_ORIGEM", DbType="Int NOT NULL")]
		public int ID_SCV_CENTRO_OPERACAO_ORIGEM
		{
			get
			{
				return this._ID_SCV_CENTRO_OPERACAO_ORIGEM;
			}
			set
			{
				if ((this._ID_SCV_CENTRO_OPERACAO_ORIGEM != value))
				{
					this._ID_SCV_CENTRO_OPERACAO_ORIGEM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_SCV_CENTRO_OPERACAO_DESTINO", DbType="Int NOT NULL")]
		public int ID_SCV_CENTRO_OPERACAO_DESTINO
		{
			get
			{
				return this._ID_SCV_CENTRO_OPERACAO_DESTINO;
			}
			set
			{
				if ((this._ID_SCV_CENTRO_OPERACAO_DESTINO != value))
				{
					this._ID_SCV_CENTRO_OPERACAO_DESTINO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NUMERO_VOO", DbType="VarChar(8000)")]
		public string NUMERO_VOO
		{
			get
			{
				return this._NUMERO_VOO;
			}
			set
			{
				if ((this._NUMERO_VOO != value))
				{
					this._NUMERO_VOO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DT_VOO", DbType="DateTime NOT NULL")]
		public System.DateTime DT_VOO
		{
			get
			{
				return this._DT_VOO;
			}
			set
			{
				if ((this._DT_VOO != value))
				{
					this._DT_VOO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DT_CADASTRO", DbType="DateTime NOT NULL")]
		public System.DateTime DT_CADASTRO
		{
			get
			{
				return this._DT_CADASTRO;
			}
			set
			{
				if ((this._DT_CADASTRO != value))
				{
					this._DT_CADASTRO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DT_ATUALIZACAO", DbType="DateTime NOT NULL")]
		public System.DateTime DT_ATUALIZACAO
		{
			get
			{
				return this._DT_ATUALIZACAO;
			}
			set
			{
				if ((this._DT_ATUALIZACAO != value))
				{
					this._DT_ATUALIZACAO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NM_COMPANHIA", DbType="VarChar(150) NOT NULL", CanBeNull=false)]
		public string NM_COMPANHIA
		{
			get
			{
				return this._NM_COMPANHIA;
			}
			set
			{
				if ((this._NM_COMPANHIA != value))
				{
					this._NM_COMPANHIA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMPANHIA_ICAO", DbType="VarChar(3) NOT NULL", CanBeNull=false)]
		public string COMPANHIA_ICAO
		{
			get
			{
				return this._COMPANHIA_ICAO;
			}
			set
			{
				if ((this._COMPANHIA_ICAO != value))
				{
					this._COMPANHIA_ICAO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NM_NOME_AERONAVE", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string NM_NOME_AERONAVE
		{
			get
			{
				return this._NM_NOME_AERONAVE;
			}
			set
			{
				if ((this._NM_NOME_AERONAVE != value))
				{
					this._NM_NOME_AERONAVE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NM_MATRICULA", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string NM_MATRICULA
		{
			get
			{
				return this._NM_MATRICULA;
			}
			set
			{
				if ((this._NM_MATRICULA != value))
				{
					this._NM_MATRICULA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NR_SERIE", DbType="BigInt NOT NULL")]
		public long NR_SERIE
		{
			get
			{
				return this._NR_SERIE;
			}
			set
			{
				if ((this._NR_SERIE != value))
				{
					this._NR_SERIE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CENTRO_OPERACAO_ORIGEM", DbType="VarChar(4) NOT NULL", CanBeNull=false)]
		public string CENTRO_OPERACAO_ORIGEM
		{
			get
			{
				return this._CENTRO_OPERACAO_ORIGEM;
			}
			set
			{
				if ((this._CENTRO_OPERACAO_ORIGEM != value))
				{
					this._CENTRO_OPERACAO_ORIGEM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CENTRO_OPERACAO_DESTINO", DbType="VarChar(4) NOT NULL", CanBeNull=false)]
		public string CENTRO_OPERACAO_DESTINO
		{
			get
			{
				return this._CENTRO_OPERACAO_DESTINO;
			}
			set
			{
				if ((this._CENTRO_OPERACAO_DESTINO != value))
				{
					this._CENTRO_OPERACAO_DESTINO = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
